print('====== DESAFIO 007 ======')
nome = str(input('Informe o nome do aluno - > '))
nota1 = float(input('Insira a primeira nota: '))
nota2 = float(input('Insira a segunda nota: '))
media = ((nota1 + nota2) / 2)
print(f' Aluno - {nome} \n Primeira nota -> {nota1}')
print(f' Segunda nota -> {nota2} \n Média do aluno -> {media:.2f}')
